//
//  UserDetailRouter.swift
//  Placeholder
//
//  Created by Eduardo Iglesias Fernández on 09/06/2020.
//  Copyright (c) 2020 Rindus. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol UserDetailRoutingLogic
{
  func routeToTodosList()
}

protocol UserDetailDataPassing
{
  var dataStore: UserDetailDataStore? { get }
}

class UserDetailRouter: NSObject, UserDetailRoutingLogic, UserDetailDataPassing
{
    // MARK: - Public Properties
    
  weak var viewController: UserDetailViewController?
  var dataStore: UserDetailDataStore?
  
  // MARK: - UsersListRoutingLogic
    
    func routeToTodosList() {
        
        let storyboard = UIStoryboard(name: Constants.Storyboards.TodosList, bundle: nil)
        let destinationVC = storyboard.instantiateViewController(withIdentifier: Constants.ViewControllers.TodosList) as! TodosListViewController
        var destinationDS = destinationVC.router?.dataStore
        passDataTodosList(source: dataStore!, destination: &destinationDS)
        navigateTodosList(source: viewController!, destination: destinationVC)
    }

  // MARK: Navigation
  
  func navigateTodosList(source: UserDetailViewController, destination: TodosListViewController)
  {
    source.show(destination, sender: nil)
  }
  
  // MARK: Passing data
  
  func passDataTodosList(source: UserDetailDataStore?, destination: inout TodosListDataStore?)
  {
    destination?.title = source?.selectedUser?.name ?? ""
    destination?.userId = "\(source?.selectedUser?.id ?? 0)"
  }
}
