//
//  TodosListRouter.swift
//  Placeholder
//
//  Created by Eduardo Iglesias Fernández on 10/06/2020.
//  Copyright (c) 2020 Rindus. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol TodosListRoutingLogic {}

protocol TodosListDataPassing {
    var dataStore: TodosListDataStore? { get }
}

class TodosListRouter: NSObject, TodosListRoutingLogic, TodosListDataPassing {
    // MARK: - Public Properties
    
  weak var viewController: TodosListViewController?
  var dataStore: TodosListDataStore?
  
  // MARK: - TodosListRoutingLogic
    
    
  // MARK: Navigation
    
  
  // MARK: Passing data
  
}
