//
//  TodosListPresenter.swift
//  Placeholder
//
//  Created by Eduardo Iglesias Fernández on 10/06/2020.
//  Copyright (c) 2020 Rindus. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol TodosListPresentationLogic {
    func presentNavBarData(_ response: TodosList.UpdateNavBar.Response)
    func presentNoDataText(_ response: TodosList.SetText.Response)
    func presentFetchedTodos(_ response: TodosList.FetchTodos.Response)
}

class TodosListPresenter: TodosListPresentationLogic {
    weak var viewController: TodosListDisplayLogic?
    
    // MARK: - TodosListPresentationLogic
    
    func presentNavBarData(_ response: TodosList.UpdateNavBar.Response) {
        let viewModel = TodosList.UpdateNavBar.ViewModel(
            navData: response.navData)
        viewController?.displayNavBarData(viewModel)
    }
    
    func presentNoDataText(_ response: TodosList.SetText.Response) {
        let viewModel = TodosList.SetText.ViewModel(
            noDataText: response.noDataText)
        viewController?.displayNoDataText(viewModel)
    }
    
    func presentFetchedTodos(_ response: TodosList.FetchTodos.Response) {
        let viewModel = TodosList.FetchTodos.ViewModel(todos: response.todos, error: response.error)

      viewController?.displayFetchedTodos(viewModel)
    }
}
