//
//  UsersListWorker.swift
//  Placeholder
//
//  Created by Eduardo Iglesias Fernández on 09/06/2020.
//  Copyright (c) 2020 Rindus. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import Foundation

protocol UsersListWorkingLogic {
    /// Request to API for loading list of users
    func fetchUsers(completion: @escaping (Result<[User]>) -> Void)
}

final class UsersListWorker: UsersListWorkingLogic {
    
    // MARK: - Private Properties
    private let networkWorker: NetworkWorkingLogic = NetworkWorker()
    private func usersURL() -> URL { return getUrl(for: Constants.URL.Users)}
    
    // MARK: - UsersListWorkingLogic
    
    func fetchUsers(completion: @escaping (Result<[User]>) -> Void) {
        let url = usersURL()
        let requestUrl = url
        var request = URLRequest(url: requestUrl)
        request.httpMethod = Constants.HTTPMethod.GET
        
        networkWorker.request(for: request, completion: completion)
    }
}
