//
//  UsersListRouter.swift
//  Placeholder
//
//  Created by Eduardo Iglesias Fernández on 07/06/2020.
//  Copyright (c) 2020 Rindus. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol UsersListRoutingLogic {
  func routeToUserDetail()
}

protocol UsersListDataPassing {
    var dataStore: UsersListDataStore? { get }
}

class UsersListRouter: NSObject, UsersListRoutingLogic, UsersListDataPassing {
    // MARK: - Public Properties
    
  weak var viewController: UsersListViewController?
  var dataStore: UsersListDataStore?
  
  // MARK: - UsersListRoutingLogic
    
    func routeToUserDetail() {

            let storyboard = UIStoryboard(name: Constants.Storyboards.UserDetail, bundle: nil)
            let destinationVC = storyboard.instantiateViewController(withIdentifier: Constants.ViewControllers.UserDetail) as! UserDetailViewController
            var destinationDS = destinationVC.router?.dataStore
            passDataToUserDetail(source: dataStore!, destination: &destinationDS)
            navigateToUserDetail(source: viewController!, destination: destinationVC)
    }
    
    // MARK: Navigation
    
    func navigateToUserDetail(source: UsersListViewController, destination: UserDetailViewController) {
      source.show(destination, sender: nil)
    }
  
  // MARK: Passing data
  
  func passDataToUserDetail(source: UsersListDataStore?, destination: inout UserDetailDataStore?) {
    destination?.selectedUser = source?.selectedUser
  }
}
